### ISSUE TITLE
Add tags to Post List Page

### ISSUE THREAD

**Issue by ManojKiranA** [merakiui/blog#7]

**Comment by khatabwedaa** [comment]
Can you give me example image, description, etc .

**Comment by ManojKiranA** [comment]
Sorry for the confusion. I mean add tags and category to single post page like this

![image](https://user-images.githubusercontent.com/30294553/90463611-0448a580-e129-11ea-83e0-1caf2850bb22.png)

**Comment by khatabwedaa** [comment]
I put the category on the top right. laravel, design, PHP that where I'm put the category
![Screenshot from 2020-08-18 10-02-16](https://user-images.githubusercontent.com/38974561/90486939-07985d00-e13a-11ea-89c2-71fc502e5414.png)
